version: '3'
services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./:/yarilog-back
      # node_modukes は volumes 管理にしたいが typescript だとホスト側にも実態が無いと import エラーとかが editer で出てしまう
      # - node-modules-data:/yarilog-front/node_modules
    command: sh -c "yarn && yarn run start:dev"
    links:
      - db
    tty: true
    ports:
      - 8080:3000
    working_dir: /yarilog-back
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "yarilog"
    ports:
      - 3306:3306
volumes:
  mysql-data:
    driver: local
  # node-modules-data:
